---
title: "hw2"
author: "Kee-Young Shin"
date: "September 29, 2018"
output: github_document
---

## Problem 1
### Create subdirectory
```{r}
library(tidyverse)


dir.create("./hw2data")

```

```{r}

transit_data = read.csv("./hw2data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>% # clean name of data
  select(line:route11, entry, entrance_type, vending, ada) %>% # filter columns 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))  # convert character into logical
  
transit_data
dim(transit_data)


distinct(transit_data, line, station_name) # Count number of distinct stations

y = distinct(transit_data, line, station_name, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11)

sum(transit_data$ada == "TRUE") # Count how many stations are ADA compliant

transit_data %>%
	filter(vending == "NO") %>%  # show only entrances without vending 
  summarize(total = n(), yes = sum(entry == "TRUE")) %>% # find number of allowed entries
  mutate(prop = yes / total) # find proportion 

	





```

## Problem 2

```{r}
library(readxl)

wheel_data = read_excel("./hw2data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
	  sheet = 1, range = cell_cols("A:N")) %>%
	  janitor::clean_names() %>% # import data and clean names
    filter(!is.na(dumpster)) %>%
    mutate(sports_balls = as.integer(round(sports_balls)))
   
	
wheel_data

prcp_2018 = read_excel("./hw2data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                       sheet = "2018 Precipitation", skip = 1 ) %>%
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(year = 2018)

prcp_2018

prcp_2017 = read_excel("./hw2data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                       sheet = "2017 Precipitation", skip = 1 ) %>%
  janitor::clean_names() %>%
  na.omit() %>%
  mutate(year = 2017)

prcp_2017

month_df = data.frame(month = 1:12, name = month.name, stringsAsFactors = FALSE)

combined_prcp = bind_rows(prcp_2018, prcp_2017) 
  

combined_prcp = inner_join(combined_prcp, month_df, by = "month")

combined_prcp

combined_prcp %>%
  filter(year == 2018) %>%
  summarize(total = sum(total))
combined_prcp %>%
  filter(year == 2017) %>%
  summarize(total = sum(total))
wheel_data %>%
  filter(year == 2017) %>%
  summarize(median = median(sports_balls))



```


## Problem 3
```{r}
devtools::install_github("p8105/p8105.datasets")

library(p8105.datasets)

data("brfss_smart2010")

brfss_smart2010


filtered_brfss = brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  select(-class, -topic, -question, -sample_size, -(confidence_limit_low:geo_location)) %>%
  spread(key = "response", value = "data_value") %>%  # making rows into columns
  janitor::clean_names() %>% # clean new columns 
  mutate(exc_very_prop = excellent + very_good) # create proportion column

filtered_brfss  

distinct(filtered_brfss, locationdesc) # distinct locations
# There are 404 distinct locations represented in this data set.
distinct(filtered_brfss, locationabbr) # distinct states
# All states are represented in addition to D.C.
head(subset(filtered_brfss, select = locationdesc))



filtered_brfss %>%
  filter(year == 2002) %>% # filter by year 2002
  summarize(median = median(excellent, na.rm = TRUE)) # show median for excellent

ggplot(filter(filtered_brfss, year == 2002 & !is.na(excellent)), aes(x = excellent)) + geom_histogram()

filtered_brfss %>%
  filter(locationdesc %in% c("NY - New York County", "NY - Queens County")) %>%
  ggplot(aes(x = year, y = exc_very_prop, color = locationdesc)) +
  geom_point()

```


